package lib.Report;

public enum SelectorTypes
{
    HISTONE_MODIFICATIONS, GROUPS, GROUP_PAIRINGS, EMPTY_DROPDOWN, IMPORTANT_LOCI, TOP_LOG2FC, REGRESSION_CUTOFFS,
    DISTRIBUTION_OPTIONS, PERFORMANCE_CUTOFFS
}
