FROM continuumio/miniconda3

RUN conda install -c conda-forge -c bioconda -y \
    python \
    bedtools \
    gxx \
    r-base \
    r-gplots \
    r-ggplot2 \
    r-glmnet \
    r-doMC \
    r-reshape2 \
    r-gridExtra \
    pandas
