library(ehmm)
library(argparser)
library(rtracklayer)
library(GenomicRanges)

args <- commandArgs(trailingOnly = T)
parser <- arg_parser("Filtering command line parser", name = "ehmm_training_filter")
parser <- add_argument(parser, "-e", help = "enhancer bed file")
parser <- add_argument(parser, "-p", help = "promoter bed file")
parser <- add_argument(parser, "-b", help = "background bed file")
parser <- add_argument(parser, "-o", help = "output directory", default = "./")
argv <- parse_args(parser, argv = args)

message("load background, enhancer, and promoter regions")
bgRegions <- import(argv$b, format = "bed")
names(bgRegions) <- 1:length(bgRegions)
eRegions <- import(argv$e, format = "bed")
pRegions <- import(argv$p, format = "bed")
message("extract enhancer and promoter regions within background regions")
eAndBg <- findOverlapPairs(bgRegions, eRegions)
pAndBg <- findOverlapPairs(bgRegions, pRegions)
eBgRegions <- unique(eAndBg@first)
eBgRegions <- eBgRegions[width(eBgRegions)<2000]
pBgRegions <- unique(pAndBg@first)
pBgRegions <- pBgRegions[width(pBgRegions)<2000]
message("removing enhancers and promoters from background regions")
bgRegions <- bgRegions[!names(bgRegions) %in% unique(c(names(eAndBg@first), names(pAndBg@first)))]
message("writing filtered bed files")
export.bed(bgRegions, file.path(argv$o, "background.bed"))
export.bed(eBgRegions, file.path(argv$o, "enhancers.bed"))
export.bed(pBgRegions, file.path(argv$o, "promoters.bed"))
